general {
    lock_cmd = pidof hyprlock || (hyprctl switchxkblayout all 0 && hyprlock)       # не запускать повторно если уже висит
    before_sleep_cmd = loginctl lock-session    # блокировка перед сном
    after_sleep_cmd = hyprctl dispatch dpms on  # включить монитор после пробуждения
    ignore_dbus_inhibit = false                 # уважать inhibit (fullscreen, mpv и т.д.)
}

# 10 мин — выключить экраны
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 30 мин — заблокировать
listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}

# 90 мин — суспенд
listener {
    timeout = 5400
    on-timeout = systemctl suspend
}
